"""Stock

Revision ID: e637cccf2c79
Revises: a6273d9ed1a5
Create Date: 2024-10-22 21:44:52.629609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e637cccf2c79'
down_revision = 'a6273d9ed1a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_transaccion', sa.DateTime(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('entrada_salida', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventarios')
    # ### end Alembic commands ###
